#!/user/bin/env ruby 

require_relative "../enviornment"

 Api.start
hi = Cli.new
hi.hello 
food_1 = Food.new(Api.api_results["results"][0]["title"],Api.api_results["results"][0]["ingredients"])
#puts food_1.title 
#puts food_1.ingredients  
food_2 = Food.new(Api.api_results["results"][1]["title"],Api.api_results["results"][1]["ingredients"])
print Food.all 